"""finding_rewrite_stats

Revision ID: 499a4929ff0e
Revises: ca5404d8e7b8
Create Date: 2026-10-05 16:38:19.510492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499a4929ff0e'
down_revision: Union[str, None] = 'ca5404d8e7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('rewrite_attempts', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('rewrite_passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'rewrite_passed')
    op.drop_column('findings', 'rewrite_attempts')
    # ### end Alembic commands ###
